"""
Qingnang phase-0: one-click database bootstrap.

Usage (from backend/):
    python scripts/init_db.py [--postgres-password <superuser_pw>] [--db-password <app_pw>]

Steps:
  1. If --postgres-password given: idempotently create role qingnang + database qingnang.
  2. If backend/.env missing: generate it (random SECRET_KEY, DEBUG=false, PG URL).
  3. Run alembic upgrade head (create all tables).
  4. Print table list for verification.

All output is ASCII-safe.
"""
import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
ENV_FILE = BACKEND / ".env"
DB_NAME = "qingnang"
DB_USER = "qingnang"
DB_HOST = "localhost"
DB_PORT = "5432"

PSQL_CANDIDATES = [
    r"C:\Program Files\PostgreSQL\17\bin\psql.exe",
    r"C:\Program Files\PostgreSQL\16\bin\psql.exe",
    r"C:\Program Files\PostgreSQL\15\bin\psql.exe",
]


def find_psql():
    for cand in PSQL_CANDIDATES:
        if Path(cand).exists():
            return cand
    which = shutil_which("psql")
    if which:
        return which
    return None


def shutil_which(name):
    try:
        import shutil
        return shutil.which(name)
    except Exception:
        return None


def psql_run(psql, user, password, db, sql):
    env = dict(os.environ)
    env["PGPASSWORD"] = password
    args = [psql, "-U", user, "-h", DB_HOST, "-p", DB_PORT]
    if db:
        args += ["-d", db]
    args += ["-t", "-A", "-c", sql]
    r = subprocess.run(args, capture_output=True, text=True, encoding="utf-8", errors="replace", env=env)
    return r.returncode, (r.stdout or "").strip(), (r.stderr or "").strip()


def ensure_role_db(psql, super_pw, app_pw):
    rc, out, err = psql_run(psql, "postgres", super_pw, None, f"SELECT 1 FROM pg_roles WHERE rolname='{DB_USER}';")
    if rc != 0:
        print("[error] cannot connect as postgres:", err)
        sys.exit(2)
    if out != "1":
        rc, out, err = psql_run(psql, "postgres", super_pw, None, f"CREATE ROLE {DB_USER} LOGIN PASSWORD '{app_pw}';")
        if rc != 0:
            print("[error] create role failed:", err)
            sys.exit(2)
        print("[ok] role", DB_USER, "created")
    else:
        print("[ok] role", DB_USER, "exists")
    rc, out, err = psql_run(psql, "postgres", super_pw, None, f"SELECT 1 FROM pg_database WHERE datname='{DB_NAME}';")
    if out != "1":
        rc, out, err = psql_run(psql, "postgres", super_pw, None, f"CREATE DATABASE {DB_NAME} OWNER {DB_USER} ENCODING 'UTF8' TEMPLATE template0;")
        if rc != 0:
            print("[error] create database failed:", err)
            sys.exit(2)
        print("[ok] database", DB_NAME, "created")
    else:
        print("[ok] database", DB_NAME, "exists")


def ensure_env(app_pw):
    if ENV_FILE.exists():
        print("[ok] .env exists, reuse it")
        return
    secret = secrets.token_hex(32)
    url = f"postgresql+psycopg2://{DB_USER}:{app_pw}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    text = (
        "# Qingnang backend environment (generated by init_db.py)\n"
        "DEBUG=false\n"
        f"SECRET_KEY={secret}\n"
        f"DATABASE_URL={url}\n"
        'CORS_ORIGINS=["http://localhost:5173","http://127.0.0.1:5173"]\n'
        "AUTO_SEED=false\n"
    )
    ENV_FILE.write_text(text, encoding="utf-8")
    print("[ok] .env generated (random SECRET_KEY, DEBUG=false)")


def run_alembic():
    os.chdir(BACKEND)
    sys.path.insert(0, str(BACKEND))
    from alembic.config import Config
    from alembic import command
    cfg = Config(str(BACKEND / "alembic.ini"))
    print("[..] running alembic upgrade head ...")
    command.upgrade(cfg, "head")
    print("[ok] migration applied")


def verify_tables():
    try:
        from app.config import settings
        from sqlalchemy import create_engine, text
        eng = create_engine(settings.DATABASE_URL)
        with eng.connect() as conn:
            rows = conn.execute(text("SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename;")).fetchall()
        names = [r[0] for r in rows]
        print("[ok] tables in qingnang:", ", ".join(names))
        return names
    except Exception as exc:
        print("[warn] verify failed:", exc)
        return []


def main():
    ap = argparse.ArgumentParser(description="Qingnang phase-0 DB bootstrap")
    ap.add_argument("--postgres-password", default="", help="superuser password for creating role/db (idempotent)")
    ap.add_argument("--db-password", default="", help="app db password (only used when creating role or .env)")
    args = ap.parse_args()

    app_pw = args.db_password
    if not app_pw:
        import re
        m = re.search(r"://\w+:([^@]+)@", (ENV_FILE.read_text(encoding="utf-8") if ENV_FILE.exists() else ""))
        if m:
            app_pw = m.group(1)
    if not app_pw:
        app_pw = "".join(secrets.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789") for _ in range(24))

    psql = find_psql()
    if args.postgres_password:
        if not psql:
            print("[error] psql not found; install PostgreSQL or pass --postgres-password after install")
            sys.exit(2)
        ensure_role_db(psql, args.postgres_password, app_pw)
    else:
        print("[skip] role/db creation skipped (pass --postgres-password to enable)")

    ensure_env(app_pw)
    run_alembic()
    verify_tables()
    print("Done. Start backend with: python run.py")


if __name__ == "__main__":
    main()
