"""init schema

Revision ID: 1e57d54d7a5b
Revises: 
Create Date: 2026-09-26 18:21:25.669570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e57d54d7a5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hospital', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('license_no', sa.String(length=50), nullable=True),
    sa.Column('license_img', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('provider_url', sa.String(length=500), nullable=True),
    sa.Column('spum_tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_items_sku'), 'shop_items', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qingnang_id', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=4), nullable=True),
    sa.Column('birth_date', sa.String(length=10), nullable=True),
    sa.Column('birth_hour', sa.String(length=10), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_doctor', sa.Boolean(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('v_base', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_qingnang_id'), 'users', ['qingnang_id'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bazi', sa.String(length=30), nullable=True),
    sa.Column('ganzhi_year', sa.String(length=10), nullable=True),
    sa.Column('ganzhi_month', sa.String(length=10), nullable=True),
    sa.Column('ganzhi_day', sa.String(length=10), nullable=True),
    sa.Column('v_innate', sa.JSON(), nullable=True),
    sa.Column('v_baseline', sa.JSON(), nullable=True),
    sa.Column('v_current', sa.JSON(), nullable=True),
    sa.Column('syndrome', sa.String(length=100), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('current_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=True)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('rule', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_creator_id'), 'challenges', ['creator_id'], unique=False)
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(length=20), nullable=True),
    sa.Column('is_doctor_bind', sa.Boolean(), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('bind_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_friend_id'), 'friends', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friends_user_id'), 'friends', ['user_id'], unique=False)
    op.create_table('shop_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_orders_external_id'), 'shop_orders', ['external_id'], unique=True)
    op.create_index(op.f('ix_shop_orders_user_id'), 'shop_orders', ['user_id'], unique=False)
    op.create_table('shop_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('wuxing_feel', sa.JSON(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('ai_annotated', sa.Boolean(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('flagged_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_reviews_item_id'), 'shop_reviews', ['item_id'], unique=False)
    op.create_index(op.f('ix_shop_reviews_user_id'), 'shop_reviews', ['user_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('checkin_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_challenge_id'), 'checkins', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('sqi', sa.Float(), nullable=True),
    sa.Column('ppg_wave', sa.JSON(), nullable=True),
    sa.Column('delta_f', sa.JSON(), nullable=True),
    sa.Column('v_obs', sa.JSON(), nullable=True),
    sa.Column('syndrome_hint', sa.String(length=200), nullable=True),
    sa.Column('observed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_case_id'), 'observations', ['case_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('herbs', sa.JSON(), nullable=True),
    sa.Column('life_advice', sa.JSON(), nullable=True),
    sa.Column('avoidances', sa.JSON(), nullable=True),
    sa.Column('from_obs_id', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('doctor_signed', sa.Boolean(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=True),
    sa.Column('effectiveness', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_case_id'), 'treatment_plans', ['case_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('fb_type', sa.String(length=30), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('wuxing_effect', sa.JSON(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('ai_annotated', sa.Boolean(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('flagged_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_plan_id'), 'feedbacks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_plan_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_treatment_plans_case_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_observations_case_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_challenge_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_shop_reviews_user_id'), table_name='shop_reviews')
    op.drop_index(op.f('ix_shop_reviews_item_id'), table_name='shop_reviews')
    op.drop_table('shop_reviews')
    op.drop_index(op.f('ix_shop_orders_user_id'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_external_id'), table_name='shop_orders')
    op.drop_table('shop_orders')
    op.drop_index(op.f('ix_friends_user_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_friend_id'), table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_challenges_creator_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_qingnang_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shop_items_sku'), table_name='shop_items')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    # ### end Alembic commands ###
