"""add is_member to users

Revision ID: f18fc84bf775
Revises: 4a5b6c7d8e9f
Create Date: 2026-10-04 10:25:02.331746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f18fc84bf775'
down_revision: Union[str, None] = '4a5b6c7d8e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inquiry_sessions_case_id'), 'inquiry_sessions', ['case_id'], unique=False)
    op.alter_column('trajectory_events', 'damage',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('trajectory_events', 'boost',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('trajectory_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trajectory_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trajectory_events_case_id'), 'trajectory_events', ['case_id'], unique=False)
    op.add_column('treatment_plans', sa.Column('expected_delta_S', sa.JSON(), nullable=True))
    op.add_column('treatment_plans', sa.Column('outcome_delta_S', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_member', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('users', 'dev_seed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_users_wechat_openid', 'users', type_='unique')
    op.drop_constraint('uq_users_wechat_unionid', 'users', type_='unique')
    op.drop_index('ix_users_wechat_openid', table_name='users')
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    op.drop_index('ix_users_wechat_unionid', table_name='users')
    op.create_index(op.f('ix_users_wechat_unionid'), 'users', ['wechat_unionid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wechat_unionid'), table_name='users')
    op.create_index('ix_users_wechat_unionid', 'users', ['wechat_unionid'], unique=False)
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.create_index('ix_users_wechat_openid', 'users', ['wechat_openid'], unique=False)
    op.create_unique_constraint('uq_users_wechat_unionid', 'users', ['wechat_unionid'])
    op.create_unique_constraint('uq_users_wechat_openid', 'users', ['wechat_openid'])
    op.alter_column('users', 'dev_seed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'is_member')
    op.drop_column('treatment_plans', 'outcome_delta_S')
    op.drop_column('treatment_plans', 'expected_delta_S')
    op.drop_index(op.f('ix_trajectory_events_case_id'), table_name='trajectory_events')
    op.alter_column('trajectory_events', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trajectory_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trajectory_events', 'boost',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trajectory_events', 'damage',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_inquiry_sessions_case_id'), table_name='inquiry_sessions')
    # ### end Alembic commands ###
